---
title: "Final Project_Clean Visualization Data"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    df_print: paged
    theme: flatly
    highlight: pygments
---
# 0 Summary of File
The purpose of this file is to summarize and reshape the dataset of the Top 100 Recruits from 2010-2020 for the purpose of data visualization, specifically cluster bar graphs. 

#1 Setup environment
```{r}
# remove all objects
rm(list=ls())

# check working directory
getwd()

# Unload all packages 
library(pacman)
pacman::p_unload(all)

# Add packages 
pacman::p_load(
  tidyverse, #ggplot, dplyr, readr, etc.
  ggthemes, #extra themes
  viridis, #great colors
  data.table, #fread() 
  foreign, #load data types including stata .dta files 
  magrittr, #%<>% operator
  skimr, #for summerising
  stargazer, #pretty tables 
  xtable, #pretty tables 
  knitr #pretty tables (kable)
)
```

#2 Load Data 
```{r}
bar_graph_data <- read.csv("/Users/jasminesanders/Desktop/Berkeley/Spring 2020/239T Intro to Computational Tools/Final_Project/top_100_2010-2020_csv.csv")
```

#3 Summarize Data
```{r}
bar_graph_data %>% glimpse()
```

#4 Functions
```{r}
freqTable <- function(datName, x){
  datName %>% 
    group_by_(x) %>% 
    summarise(total=n(),
              pct=round(total/nrow(datName)*100,1)) %>% 
    arrange(desc(total)) %>%
    print()
}

eval(parse(text="freqTable(bar_graph_data,'HS.Type')"))
```

#5 Reshaping Data
```{r}
# Frequency of hs type
HStype_by_year <- bar_graph_data %>% 
  group_by(HS.Type, Year) %>% 
  summarise(total=n()) %>%
  print()

# Spread out totals by year 
HStype_by_year %>% 
  spread(key=Year, value=total)

# Restack data for bar graphs
cluster_bar_graph <- HStype_by_year %>% 
  spread(key=Year, value=total) %>%
  gather(key=year_new, value=total_new, -HS.Type)
print(cluster_bar_graph)
```

#6 Save Data
```{r}
write.csv(cluster_bar_graph, "/Users/jasminesanders/Desktop/Berkeley/Spring 2020/239T Intro to Computational Tools/Final_Project/reformatted data.csv")
```


